[package]
name = "indexa"
version = "0.1.0"
authors = ["mosm <airman515@gmail.com>"]
edition = "2018"

[lib]
name = "indexa"
path = "src/lib.rs"

[[bin]]
name = "ix"
path = "src/bin/ix/main.rs"

[dependencies]
anyhow = "1.0.31"
bincode = "1.2.1"
cassowary = "0.3.0"
chrono = "0.4.11"
clap = "2.33.1"
crossbeam-channel = "0.4.2"
crossterm = "0.17.5"
dirs = "3.0.0"
dunce = "1.0.1"
enum-map = { version = "0.6.2", features = ["serde"] }
itertools = "0.9.0"
num_cpus = "1.13.0"
rayon = "1.3.0"
regex = "1.3.9"
serde = { version = "1.0.111", features = ["derive"] }
size = "0.1.2"
structopt = "0.3.14"
strum = "0.18.0"
strum_macros = "0.18.0"
thiserror = "1.0.19"
toml = "0.5.6"
tui = { version = "0.9.5", features = ["crossterm"], default-features = false }
unicode-segmentation = "1.6.0"
unicode-width = "0.1.7"

[dev-dependencies]
tempfile = "3.1.0"
