[package]
name = "indexa"
version = "0.1.0"
authors = ["mosm <airman515@gmail.com>"]
edition = "2018"

description = "A locate alternative with incremental search"
repository = "https://github.com/mosmeh/indexa"
documentation = "https://github.com/mosmeh/indexa"
homepage = "https://github.com/mosmeh/indexa"

readme = "README.md"
license-file = "LICENSE"
categories = ["command-line-utilities"]
keywords = ["search", "files", "command-line"]
exclude = [
    "/assets",
    "/config"
]

[lib]
name = "indexa"
path = "src/lib.rs"

[[bin]]
name = "ix"
path = "src/bin/ix/main.rs"
doc = false

[dependencies]
anyhow = "1.0.40"
bincode = "1.3.3"
cassowary = "0.3.0"
chrono = "0.4.19"
console = "0.14.1"
crossbeam-channel = "0.5.1"
crossterm = "0.19.0"
dialoguer = "0.8.0"
dirs = "3.0.2"
dunce = "1.0.1"
enum-map = { version = "1.1.0", features = ["serde"] }
itertools = "0.10.0"
num_cpus = "1.13.0"
parking_lot = "0.11.1"
rayon = "1.5.0"
regex = "1.5.4"
regex-syntax = "0.6.25"
serde = { version = "1.0.126", features = ["derive"] }
size = "0.1.2"
structopt = "0.3.21"
strum = "0.20.0"
strum_macros = "0.20.1"
thiserror = "1.0.24"
toml = "0.5.8"
tui = { version = "0.9.5", features = ["crossterm"], default-features = false }
unicode-segmentation = "1.7.1"
unicode-width = "0.1.8"

[dev-dependencies]
tempfile = "3.2.0"

[profile.release]
lto = true
codegen-units = 1
