# Default indexa configuration file.

[flags]
# Default values for command-line flags.
# Flags provided to CLI will override this group of options.

# Initial query.
# query = "blah blah"

# Whether to search case-sensitively.
# Defaults to smart case.
# case_sensitive = false

# Whether to search case-insensitively.
# Defaults to smart case.
# ignore_case = false

# Whether to search in path.
# match_path = false

# Whether to search in path when query contains path separators.
# auto_match_path = false

# Whether to enable regex.
# regex = true

# Number of threads to use.
# Defaults to the number of available CPUs - 1.
# threads = 4

[database]
# Location of database file. Defaults to {user's data directory}/indexa/database.db
# location = "/path/to/database/database.db"

# File/directory statuses to index.
# basename, path and extension are implicitly specified.
index = [
    # "size",
    # "mode",
    # "created",
    # "modified",
    # "accessed",
]

# File/directory statuses to enable fast sorting for.
# basename is implicitly specified.
fast_sort = [
    # "path",
    # "extension",
    # "size",
    # "mode",
    # "created",
    # "modified",
    # "accessed",
]

# Root directories to index. Defaults to / on Unix and %HOMEDRIVE%\ (usually C:\) on Windows.
# dirs = [
#     "/",
# ]

# Whether to ignore hidden files/directories.
ignore_hidden = false

[ui]
# File/directory status to sort by.
sort_by = "basename"
# sort_by = "path"
# sort_by = "extension"
# sort_by = "size"
# sort_by = "mode"
# sort_by = "created"
# sort_by = "modified"
# sort_by = "accessed"

# Sort order.
sort_order = "ascending"
# sort_order = "descending"

# Whether to sort directories before files.
sort_dirs_before_files = false

# Whether to show size in human readable format.
human_readable_size = true

# Datetime format for Created, Modified, and Accessed columns.
datetime_format = "%Y-%m-%d %R"

# Margin between columns.
column_spacing = 2

# Columns from left to right.
# Columns with width specified will have fixed widths.
# Remaining screen width is evenly distributed among other columns.
[[ui.columns]]
status = "basename"

[[ui.columns]]
status = "size"
width = 10

[[ui.columns]]
status = "modified"
width = 16

[[ui.columns]]
status = "path"

[ui.unix]
# Format of mode column.
mode_format = "symbolic"
# mode_format = "octal"

[ui.windows]
# Format of mode column.
mode_format = "traditional"
# mode_format = "powershell"

[ui.colors]
# Colors in one of following formats:
# - Color name
#     reset, black, white, red, green, yellow, blue, magenta, cyan, gray, darkgray,
#     lightred, lightgreen, lightyellow, lightblue, lightmagenta, lightcyan
# - RGB e.g. "66, 135, 245"
# - Hex e.g. "#e43", "#fcba03"

# Text (selected line)
selected_fg = "lightblue"
# Background (selected line)
selected_bg = "reset"

# Text (matched substring)
matched_fg = "black"
# Background (matched substring)
matched_bg = "lightblue"

# Text (error message)
error_fg = "red"
# Background (error message)
error_bg = "reset"

# Prompt
prompt = "lightblue"
