# A config imitating the default options of Everything (https://www.voidtools.com/)

[flags]
ignore_case = true
match_path = "auto"

[database]
index = [
    "size",
    "modified",
]
fast_sort = [
    "path",
    "size",
    "modified",
]

[ui]
sort_dirs_before_files = true

[[ui.columns]]
status = "basename"
width = 50

[[ui.columns]]
status = "path"

[[ui.columns]]
status = "size"
width = 15

[[ui.columns]]
status = "modified"
width = 16
