[flags]
auto_match_path = true

[database]
index = [
    "size",
    "mode",
    "modified"
]
fast_sort = ["modified"]

[ui]
sort_by = "modified"
sort_order = "descending"
human_readable_size = true
datetime_format = "%Y/%m/%d %T"

[[ui.columns]]
status = "basename"

[[ui.columns]]
status = "mode"
width = 8

[[ui.columns]]
status = "size"
width = 9

[[ui.columns]]
status = "modified"
width = 20

[[ui.columns]]
status = "path"

[ui.unix]
mode_format = "symbolic"

[ui.windows]
mode_format = "traditional"
