name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        rust: [stable, beta, nightly]
        include:
        - os: macos-10.15
          rust: stable
        - os: windows-2019
          rust: stable
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
        components: rustfmt, clippy
    - run: cargo build --verbose
    - run: cargo test --verbose
    - run: cargo fmt --all -- --check
    - run: cargo clippy -- -D warnings
